config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get 'signup', to:'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user

	validates :title, presence: true, length: {minimum:5, maximum: 100}
	validates :description, presence: true, length: {minimum:5, maximum: 500}
	validates :keywords, presence: true, length: {minimum:5}

	has_many_attached :images

	def self.order_by_created_at_desc
		order(created_at: :desc)
	end
end

app/models/user.rb
class User < ApplicationRecord
	before_save {email = self.email.downcase}
	has_many :posts
	
	validates :username, presence: true, length:{minimum: 3, maximum: 25}, uniqueness: {case_sensitive: false}
	VALID_EMAIL_REGEX = /([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/
	validates :email, presence: true, length:{maximum: 105}, uniqueness: {case_sensitive: false},
										format: {with: VALID_EMAIL_REGEX}
	has_secure_password	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order_by_created_at_desc
    end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.first

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, images: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			redirect_to user, notice: "Welcome #{user.username}, you are succesfully loged in"
		else
			flash.now[:alert] = "Something is wrong with your login informations"
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Succesfully loged out"
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to posts_path, notice: "Welcome #{@user.username}" }
        format.json { render :show, status: :created, location: posts_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "#{@user.username} update successfull" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end


	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<h1>Vítej na mém instagram klonu</h1>
<p>tohle je jen pokus o static stránku. Takové about</p>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer">
	<div class="container-fluid text-center py-4 bg-dark mt-4 text-white">
		Copyright &copy; <%= link_to "Richard Kachyňa","https://github.com/Tacud1810", class:"text-white" %>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if name == "notice" %>
    <div style="color: green" >
      <%= msg %>
    </div>  
    <br> 
    <% else %>
    <div style="color: red">
      <%= msg %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          
        </li>
        <li class="nav-item">
          <%= link_to "Upload post", new_post_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About us", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", login_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", login_path, class:"nav-link", data: {turbo_method: :delete} %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySchoolInsta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="content col-xl-6 col-sm-6 col-sm-8 col-10" style="margin: auto; background-color: #f8f8f8; border-radius:20px; padding: 15px">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>

  <div>
    <% invalid = post.errors.include?(:title) %>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
    <% if invalid %>
      <% post.errors.full_messages_for(:title).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>

  <div>
    <% invalid = post.errors.include?(:description) %>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control" %>
    <% if invalid %>
      <% post.errors.full_messages_for(:description).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>

  <div>
    <% invalid = post.errors.include?(:keywords) %>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords, class:"form-control" %>
    <% if invalid %>
      <% post.errors.full_messages_for(:keywords).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.file_field :images, multiple:true %>
  </div>
  <br>
  <div>
    <%= form.submit class:"btn btn-primary col-12" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div style="text-align: left">
  by <%= link_to post.user.username, post.user if post.user %>
</div>
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <%= post.title %>
  </p>

  <p>
    <%= post.description %>
  </p>

  <p>
    <%= post.keywords %>
  </p>
  <p>
    <%= link_to "", post, class:"post-link" %>
  </p>
  <div>
    <% post.images.each do |image| %>
      <%= image_tag(image, style: "object-fit: contain; width: 300px; height: 400px;") %>
    <% end %>
  </div>  
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>

<%= render "layouts/messages" %>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <div>
    <% invalid = user.errors.include?(:username) %>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, class:"form-control" %>
    <% if invalid %>
      <% user.errors.full_messages_for(:username).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>

  <div>
    <% invalid = user.errors.include?(:email) %>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, class:"form-control" %>
    <% if invalid %>
      <% user.errors.full_messages_for(:email).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>

  <div>
    <% invalid = user.errors.include?(:password) %>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, class:"form-control" %>
    <% if invalid %>
      <% user.errors.full_messages_for(:password).each do |error|%>
      <li style="color: red"><%= error %></li>
      <% end %>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-primary col-12") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" >
  <p>
    Username: <%= user.username %>
  </p>

  <p>
    User email: <%= user.email %>
  </p>
   <p>
    <%= pluralize(user.posts.count, "post") %> 
  </p>

</div>
<div>
  <%= link_to "View this user", user %> |
  <%= link_to "Edit this user", edit_user_path(user) %> |
  <%= link_to "Destroy this user", @user, method: :delete, style:"color: red" %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag("post") %>

<%= render "layouts/messages" %>

<div id="posts">
  
    <% @users.each do |user| %>
    <div class="post-container">
      <%= render user %>
        </div>
    <% end %>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="text-align: center"><%= @user.username %>'s profile</h1>
<%= render @user %>
<h3 style="text-align: center">
  Posts
</h3>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    
  <% end %>
</div>